# SPDX-FileCopyrightText: 2023 fosslinux <fosslinux@aussies.space>
# SPDX-FileCopyrightText: 2025 Alexandre Gomes Gaigalas <alganet@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  job_lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: cpplint --recursive tools
      - run: sh LICENSES/verify.sh

  job_build_host_files:
    runs-on: ubuntu-24.04
    needs: job_lint
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - uses: actions/cache@v4
        id: cache-host-files
        env:
          cache-name: cache-host-files
        with:
          path: out/host
          key: build-${{ env.cache-name }}-${{ hashFiles('host.answers') }}
          restore-keys: |
            build-${{ env.cache-name }}-
            build-
      - run: sh run.sh make_host
      - uses: actions/upload-artifact@v4
        with:
          name: host_files
          path: out/host

  job_build_k0_img:
    runs-on: ubuntu-24.04
    needs: job_build_host_files
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/action_get_host_artifact
      - run: sh run.sh make_k0_img sha256sum_k0_answers
      - run: git diff --exit-code k0.answers
      - uses: actions/upload-artifact@v4
        with:
          name: k0_img
          path: out/k0.img

  job_test_k0_img:
    runs-on: ubuntu-24.04
    needs: job_build_host_files
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/action_get_host_artifact
      - name: Run seal breaking test
        run: |
          # Remove old checksum file
          rm k0.answers

          # Build k0.img with self-breaking boot (generates new checksum)
          FORCE_FAIL=yes sh run.sh make_k0_img

          # Checks before booting, it should pass
          sh run.sh sha256sum_k0_answers

          # Boots the image, it should now self-modify and break the seal
          sh run.sh boot_k0_img

          # If the check fails, this test passes
          ! sh run.sh sha256sum_k0_answers &&
            echo "'FAILED' sha256sum message here is pass, 'PASSED' means fail."

  job_boot_k0_img:
    runs-on: ubuntu-24.04
    needs: job_build_k0_img
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@v4
        with:
          name: k0_img
          path: out
      - run: sh run.sh boot_k0_img

